### ISSUE TITLE
Update Airtable & Repeatable Ops

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/DAOBot#100]
#### Airtable & Ops Requirements
- [ ] Update user's table to only have required fields (i.e. clear password, etc...)
- [ ] The "Proposal Submission" Step of the DAO OPS script needs to be updated.
https://github.com/oceanprotocol/oceandao/issues/69
- [ ] The current (R13) steps of the DAO OPS should be updated

It should reflect these requirements as well.
Whoever is entering proposals will also have to enter User information + linking it together. It's a bit more work.
1. Add users to [Users] Table
2. Link [Proposal] to [Users]

**Comment by trentmc** [comment]
Obsolete thanks to proposal portal :)
