### ISSUE TITLE
Fix issues for R14 that caused a miscount in funding distribution

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/DAOBot#137]
There is an issue in R14 that is causing a funding distribution problem.

### DoD:
- [ ] Setup a functional test that takes R14 data from Airtable, fixes the issue, and verifies that other functionality is still working.

**Comment by idiom-bytes** [comment]
Funding calculation is reporting various earmarks w/ left-over funds, however we know that is not the case. 

![Screenshot from 2022-02-07 18-15-45](https://user-images.githubusercontent.com/69865342/152905224-962163df-3c97-4789-ad75-012555dfa378.png)

**Comment by idiom-bytes** [comment]
I have built out a unit test that will make it easier to verify the fix is working, however I took the opportunity to also do a manual reconciliation of the spreadsheet in order to be able to report the winners.

https://docs.google.com/spreadsheets/d/1e4xb6m-aKcBhwob_p7ereSFneXFPpDjUbSjz13smmHI/edit#gid=2063554808

I will continue to work on sorting out the final calculation, however I believe it has something to do with how recycling funds is implemented.

**Comment by idiom-bytes** [comment]
I pushed a fix. R14 now adds up to 200k OCEAN, however, there is a specific part of the code base that could use some cleanup.

The calculations of fund distribution in the round-end are pretty messy, and there are very few tests around it. The summary report being generated has various bugs in it as well, so it's quite hard to verify that everything is working well.

**Comment by KatunaNorbert** [comment]
> Funding calculation is reporting various earmarks w/ left-over funds, however we know that is not the case.
> 
> ![Screenshot from 2022-02-07 18-15-45](https://user-images.githubusercontent.com/69865342/152905224-962163df-3c97-4789-ad75-012555dfa378.png)

Right, this values are way off, but I think this is due to the testing environment, you should have all OCEAN and USD granted fields set to 0 and make sure you have the SNAPSHOT_SPACE env variable set to get the votes, otherwise the proposals won't be taken in consideration for earmarks

**Comment by idiom-bytes** [comment]
I am working to update when logic is executed, so we can always be reporting vote count & winners.

**Comment by idiom-bytes** [comment]
I will be looking into this branch as I am updating daobot logic, so results are always being provided.
