### ISSUE TITLE
Re-Implement support for historical funding calculations.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/DAOBot#162]
### Problem:
We have tried to provide support to make Funding Round parameters, configurable.
However, new funding calculations broken our ability to switch between configurations. This [pull request updates our funding distribution and various calculations](https://github.com/oceanprotocol/DAOBot/pull/160), however it breaks a few things.

**This was done and supported because we are still exploring the problem-solution space.**

In order to keep the underlying mechanisms flexible, we need to fix the following tests. Example: Burning within earmarks stopped working.

It may be convenient to maintain previous configurations, and put QF funding distribution under a switch like other mechanisms such as QV, so that DAOBot continues to support a wide range of configurations & parameters. 

### DoD:
- [ ] Remove tests and support for historical calculations, or re-introduce it. Understand the impact and be intentional.
- [ ] This ticket may likely be removed if this functionality is moved over to the Proposal Portal, and we choose to make it only support present-requirements.

**Comment by trentmc** [comment]
The payoff is not worth the effort. closing
