### ISSUE TITLE
Fix link in readme.md

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/DAOBot#24]
The readme says:

> You can use our [Airtable API Endpoint via this link](https://airtable.com/appVer8ccYGnqSm2H/api/docs#javascript/introduction) and access it via `curl`.

but when I go there, this is what I'm seeing: 

<img width="1183" alt="Screen Shot 2021-10-19 at 17 25 45" src="https://user-images.githubusercontent.com/2758453/137942181-d4c3010a-5afc-4f12-8cfd-99fbfeb329b8.png">

Is the link broken?

**Comment by DimitarSD** [comment]
@TimDaub can you confirm that the link still doesn’t work? I managed to open it.

**Comment by idiom-bytes** [comment]
If the view is not available:
- Let's create a new view of every single table: `Proposals` & `Funding Rounds` and document the link to those.

**Comment by idiom-bytes** [comment]
I updated the links and sent it to a contact of Robin's, and it seems to be working.

Can someone review/verify this again?
@TimDaub, anyone else?
