### ISSUE TITLE
Project UUID

### ISSUE THREAD

**Issue by KinimodEtlon** [oceanprotocol/DAOBot#29]
At the moment proposals will be linked to the summary table via the "Project Name" column. Since this column and other related columns might change over time, it is not "save" to use, in order to create a complete summary. To prevent any issues when changing any of the metrics of the proposal, we should have an immutable column which holds an UUID as unique identifier for the summary.

**AC:**
- [ ] create a UUID for each [Projects Summary] table row
- [ ] link the correct Project Summary UUID to each proposal

**Comment by idiom-bytes** [comment]
@KinimodEtlon if I remember our discussions, we were chatting about having the UUID for the project.

So this UUID would exist:
- In every proposal [Proposals Table].
- In one row inside the [Project Summary] table.

This UUID would not be the same as the one generated automatically by Airtable.

Can you please confirm?
Thank you!
