### ISSUE TITLE
Ocean Protocol japan getting "Rejected" they have 500 ocean + added deliverable update in Airtable

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/DAOBot#38]
There is a transition missing. When Ocean Protocol Japan proposal was added to the airtable, the DAOBot added the status of "no ocean" although the wallet has 500 Oceans. 

### DOD:
- [ ] Fix issue inside of Ana's Airtable.
Ana has an Airtable that has this problem in there. (Ana's Table)
Claudia has been able to replicate it.
- Can we move this issue into a test w/ a mock, and replicate this issue in there?
- Can we then implement a fix for the edge case.
- [ ] Fix issue where.. If a previous proposal is "unreported" a new proposal will show up as "accepted"

**Comment by AnaLoznianu** [comment]
![Screenshot 2021-11-03 at 10.10.41.png](https://images.zenhubusercontent.com/60a2262e74d8191993b88a11/bbbba76e-e349-4fb1-83f7-9cb0ee52a490)

**Comment by idiom-bytes** [comment]
Ana has an Airtable that has this problem in there. (Ana's Table)
Claudia has been able to replicate it.
- Can we move this issue into a test w/ a mock, and replicate this issue in there?
- Can we then implement a fix for the edge case.
