### ISSUE TITLE
All the deliverables are checked but the project standing status is unreported

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/DAOBot#39]
There are a few bugs going on:
1. Ocean Japan had 2 entries. First entry was completed w/ updates + wallet had Ocean => Project was reported as `No Ocean`
2. Sometimes, the `Proposal State` doesn't update to it's correct state right away. DAOBot needs to run twice, for the state to be calculated correctly. I do not have good steps to recreate this at the moment.

**Comment by trizin** [comment]
https://github.com/oceanprotocol/DAOBot/pull/80
