### ISSUE TITLE
[Documentation] - Update readme to reflect the latest functionality inside of DAOBot.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/DAOBot#67]
Problem Statement:
- Currently, our README.md is out of date

- [ ] Add snapshot documentation
- [ ] Add new env variables with explanation
- [ ] Add a new section with information about testing
- [ ] Add icons to all sections
- [ ] GSheet usage and integration

**Comment by AnaLoznianu** [comment]
@idiom-bytes @KatunaNorbert I think catching all the updates(Read.me, functions documentation and generation) is a bit too much for a single task. I've split the work into 2. In this issue we will do updates to the Read.me files and [here](https://github.com/oceanprotocol/DAOBot/issues/76) we will add documentation to the DAOBot functions
