### ISSUE TITLE
Create Round Results GSheet table in the DD perios

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/DAOBot#86]
The goal would be to have the `Round Results` `GSheet` table created before the voting period starts in order to link it into the `Notion` Votes chart without having to wait for the Voting Period to start.
In the Dude Diligent period we already have the Proposals that would go into the snapshot so we could already show the chart.
On the other hand there is still room for changes regarding the proposals which will be accepted( for example adding Ocean to wallet and go from `Rejected` to `Accepted`), so we might need to constantly update the `Round Results` Sheet

**Comment by idiom-bytes** [comment]
I verified that this is working.

**Comment by KatunaNorbert** [comment]
ok, closing this
