### ISSUE TITLE
R13 - Update DAOBot to support Burn/Recycle Switches

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/DAOBot#95]
#### Switch (1):
- Burn
- Recycle

#### Switch (2):
- Burn
- Move to Treasury
- Move to General Category

Heuristic:
1. Process non-general category earmarks (new teams, new outreach, core tech)
2. Move left over funds to Treasury or General Category
3. Finally, process General Category
4. If there are funds available in General Category, then finally move these funds back into the Treasury.

#### For R13:
- Recycle funds
- If funds are left over in earmark, move funds to General Category

#### DOD:
- [ ] Add Switch (1) - Burn vs. Rule
- [ ] Add Switch (2) - Burn vs. Move to Treasury vs. Move to General Category Earmark

**Comment by KatunaNorbert** [comment]
Can we split this up in 2 issues, one for each switch?
